// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIjalN_q7iLo4dSuSdwLNg0QQgdrTumA',
    appId: '1:600474771630:web:38f17135807301350b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    authDomain: 'instagram-clone-8103a.firebaseapp.com',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhsUrVVtEbn065P_laYjn-EFA9YHZsmZA',
    appId: '1:600474771630:android:317b71c62a4015f40b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJL1ciOSuvRFGQNmYn_TjWumDaDakajs',
    appId: '1:600474771630:ios:26f75c149510a9bc0b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
    androidClientId: '600474771630-qnjnhestp1cnq386e2dis1a26i35k6sp.apps.googleusercontent.com',
    iosClientId: '600474771630-l03deep3j1h8p2q7nf9jh8r7hbm8bcqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyegoFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJL1ciOSuvRFGQNmYn_TjWumDaDakajs',
    appId: '1:600474771630:ios:26f75c149510a9bc0b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
    androidClientId: '600474771630-qnjnhestp1cnq386e2dis1a26i35k6sp.apps.googleusercontent.com',
    iosClientId: '600474771630-l03deep3j1h8p2q7nf9jh8r7hbm8bcqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyegoFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAIjalN_q7iLo4dSuSdwLNg0QQgdrTumA',
    appId: '1:600474771630:web:731f86dfed70eb9c0b8d3f',
    messagingSenderId: '600474771630',
    projectId: 'instagram-clone-8103a',
    authDomain: 'instagram-clone-8103a.firebaseapp.com',
    storageBucket: 'instagram-clone-8103a.firebasestorage.app',
  );
}
